// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP3nlCVVX9d0TQdXXB6RiH6WeqjRVS4Ng',
    appId: '1:1050212487500:web:c49556bc652f6f699fffe9',
    messagingSenderId: '1050212487500',
    projectId: 'placement-analyzer-1a149',
    authDomain: 'placement-analyzer-1a149.firebaseapp.com',
    storageBucket: 'placement-analyzer-1a149.firebasestorage.app',
    measurementId: 'G-D2JFH4KV7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMiwDQN9XZEcb47OVGEDN-hWbdLFpfuXI',
    appId: '1:1050212487500:android:d774a53fad1014439fffe9',
    messagingSenderId: '1050212487500',
    projectId: 'placement-analyzer-1a149',
    storageBucket: 'placement-analyzer-1a149.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfL4otNa0ucF7WiQSXB4WL3AT_KwW5gfQ',
    appId: '1:1050212487500:ios:0dd9a7d2efbf739a9fffe9',
    messagingSenderId: '1050212487500',
    projectId: 'placement-analyzer-1a149',
    storageBucket: 'placement-analyzer-1a149.firebasestorage.app',
    iosBundleId: 'com.example.placementReadinessAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfL4otNa0ucF7WiQSXB4WL3AT_KwW5gfQ',
    appId: '1:1050212487500:ios:0dd9a7d2efbf739a9fffe9',
    messagingSenderId: '1050212487500',
    projectId: 'placement-analyzer-1a149',
    storageBucket: 'placement-analyzer-1a149.firebasestorage.app',
    iosBundleId: 'com.example.placementReadinessAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP3nlCVVX9d0TQdXXB6RiH6WeqjRVS4Ng',
    appId: '1:1050212487500:web:a348e02fe2378ae49fffe9',
    messagingSenderId: '1050212487500',
    projectId: 'placement-analyzer-1a149',
    authDomain: 'placement-analyzer-1a149.firebaseapp.com',
    storageBucket: 'placement-analyzer-1a149.firebasestorage.app',
    measurementId: 'G-CJ9E8JCXJL',
  );

}